server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: hbstudent1
    password: hbstudent1
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICES
  config:
    import: configserver:http://localhost:9296
resillience4j:
  Circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-calls: 5
        automatic-transition-from-open-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

#  eureka:
#    instances:
#      prefer-ip-address: true
#    client:
#      fetch-registry: true
#      register-with-eureka: true
#      service-url:
#        defaultZon: http://localhost:8761/eureka
